import Header from "./components/Header/Header.jsx"
import ProgressBar from "./components/ProgressBar.jsx"
import { Providers } from "./redux/provider.jsx";
import './page.css'
import Message from "./utils/Message.jsx";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {



 return (
 <Providers>
      <html lang="en">
        <body style={{
          background: "rgb(123,119,193)",
          background: "linear-gradient(90deg, #7b77c1 0%, #00d4ff 100%)"
        }}>
          <Message>
            <ProgressBar />
            <Header />
            {children}
          </Message>
        </body>
      </html>
 </Providers>
  )
}
