import Header from "./components/Header/Header.jsx";
import ProgressBar from "./components/ProgressBar.jsx";
import { Providers } from "./redux/provider.jsx";
import "./page.css";
import Message from "./utils/Message.jsx";
import SideBar from "./components/SideBar/SideBar.jsx";
import AuthUser from "./utils/AuthUser.jsx";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className="light bg-[#e2e2e2c2]"
        >
          <Message>
            <ProgressBar />
            <Header /> 
            <div className="flex justify-center items-center">
              <AuthUser>
                <div className="relative w-[20%] h-fit">
                  <SideBar />
                </div>
              </AuthUser>
              <div className="w-[80%]">{children}</div>
            </div>
          </Message>
        </body>
      </html>
    </Providers>
  );
}
