import Header from "./components/Header.jsx"
import ProgressBar from "./ProgressBar.jsx"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <ProgressBar />
        <Header />
        {children}
      </body>
    </html>
  )
}
